# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
   configuration: docs/source/conf.py

python:
   version: 3.6
   install:
   - requirements: requirements.txt
   - requirements: docs/requirements.txt