name: Upload Python Package

on:
  push:
    tags:
      - v*

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6 ]
        torch-version: [ 1.4, 1.7.1 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sed -i 's/^torch>=.*/torch==${{ matrix.torch-version }}/g' requirements.txt
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Tests
        run: |
          python -m unittest discover -vs ./tests/

  deploy:
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build and Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/* --skip-existing
